name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Compile the code
      - name: Compile the application
        run: javac -d out $(find . -name "*.java")

      # Step 4: Run tests (adjust based on your tests)
      - name: Run Tests
        run: java -cp out org.junit.runner.JUnitCore TestLoginApp
