name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Compile the application with dependencies
      - name: Compile the application
        run: javac -cp "libs/junit-4.13.2.jar:libs/hamcrest-core-1.3.jar:libs/mysql-connector-j-9.1.0.jar:libs/mockito-core-5.14.2.jar" -d out $(find . -name "*.java")

      # Step 4: Run Tests with dependencies
      - name: Run Tests
        run: java -cp "out:libs/junit-4.13.2.jar:libs/hamcrest-core-1.3.jar:libs/mysql-connector-j-9.1.0.jar:libs/mockito-core-5.14.2.jar" org.junit.runner.JUnitCore TestLoginApp
